### ISSUE TITLE
Error 1.21

### ISSUE THREAD

**Issue by VISION6969** [PlayPro/CoreProtect#635]
```
[18:27:16 INFO]: Villager Villager['Villager'/525742, uuid='89957f7c-ac20-453d-a260-1da04f29c51e', l='ServerLevel[world]', x=2851.22, y=57.19, z=2794.99, cpos=[178, 174], tl=190449, v=true] died, message: 'Villager was slain by Zombie'
[18:27:17 WARN]: java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[18:27:17 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[18:27:17 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[18:27:17 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[18:27:17 WARN]:        at java.base/java.util.ArrayList.writeObject(Unknown Source)
[18:27:17 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[18:27:17 WARN]:        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
[18:27:17 WARN]:        at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:27)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:49)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:27:17 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[18:27:17 WARN]: java.sql.SQLException: Illegal operation on empty result set.
[18:27:17 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[18:27:17 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[18:27:17 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[18:27:17 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[18:27:17 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:519)
[18:27:17 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1252)
[18:27:17 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:818)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:58)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:205)
[18:27:17 WARN]:        at CoreProtect-22.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[18:27:17 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

This error pops whenever a villager is killed. Please solve it

**Comment by Skullians** [comment]
v22.4 does not support 1.21.
This was fixed in v23.
It is currently only available to patrons or you can compile it yourself for free (I have a guide on the discord for that).

**Comment by TheWISPRer** [comment]
Just upgraded to V23 and still having the issue above. In particular, with entity kill logging

`[01:12:20 WARN]: java.sql.SQLException: Illegal operation on empty result set.
[01:12:20 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[01:12:20 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[01:12:20 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
[01:12:20 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
[01:12:20 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.checkRowPos(ResultSetImpl.java:541)
[01:12:20 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1304)
[01:12:20 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:852)
[01:12:20 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
[01:12:20 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:59)
[01:12:20 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[01:12:20 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
[01:12:20 WARN]:        at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[01:12:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by JanJanSnickers** [comment]
I have also the same problem. I use version 23 and the server is running 1.21.3 Paper. Also with Entity kill log.

```
[09:00:36 WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1194)
 [09:00:36 WARN]: 	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:358)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:28)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:50)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
 [09:00:36 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
 [09:00:36 WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:52)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:206)
 [09:00:36 WARN]: 	at CoreProtect-CE-23.0-RC1b.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
 [09:00:36 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by TheWISPRer** [comment]
@JanJanSnickers V23 Only works for 1.22.1. You'll need to either get the v23.2 development version from Patreon or compile it yourself. They have instructions in the Discord!

**Comment by Dragsio** [comment]
https://github.com/PlayPro/CoreProtect/issues/688#issuecomment-2548417653
